### PR TITLE
Conway

### PR DESCRIPTION
**Pull request by janmazak**

### CODE REVIEW

**Comment by gitmachtl** [comment]
just compiled this version, will start testing in a bit.

one question: how is the witnessing for the conway era stake key registration now working to get out two witnesses? or is it just one output that contains both witnesses?

**Comment by davidmisiak** [comment]
> one question: how is the witnessing for the conway era stake key registration now working to get out two witnesses? or is it just one output that contains both witnesses?

@gitmachtl Under the new implementation, all signing files are passed to Ledger/Trezor as `additionalWitnessRequests`, so a witness should be generated for each of them (@janmazak correct me if I'm wrong). So if you provide both signing files and two out files, both witnesses should be generated (even for the legacy stake registration - if you're not interested in this witness, you can ignore it, or even provide `/dev/null` as out file). The signing files and witness out files order should match.

TODO @janmazak / @davidmisiak - when releasing, mention this in release notes.

**Comment by gitmachtl** [comment]
@davidmisiak i am testing conway with @janmazak for over a week now ... i think we have to do some catch up on TG :-)

**Comment by gitmachtl** [comment]
ok, i did the COLD/HOT swap just in case that resolves the issue with the "missing signing file for certificate" issue. it did not.

here is the unwitnessed tx:
```json
{
    "type": "Unwitnessed Tx ConwayEra",
    "description": "Ledger Cddl Format",
    "cborHex": "84a5008182582096dd368a25fd084f57351cd9486251ba10061362f0d25258efa89c9c85f8c8530001818258390074976c54afaf444f7cd499bd8519aac6592b13b22b9d5817f0da5c5203d205532089ad2f7816892e2ef42849b7b52788e41b3fd43a6e01cf1a00380b4f021a0006af62031a011b610b0481830e8200581c03738df44357720b5cad09204efd460dca1fb3eeea8d1a6c061c75ff8200581c5aa349227e4068c85c03400396bcea13c7fd57d0ec78c604bc768fc5a0f5f6"
}
```

here is the payment hwsfile:
```json
{
    "type": "PaymentHWSigningFileShelley_ed25519",
    "description": "Payment Hardware Signing File",
    "path": "1852H/1815H/0H/0/0",
    "cborXPubKeyHex": "58400186abff41121414f856fd8cf613399f9a30e413bb1c75c2413f46121f020349d8426b745ca51de4f5bc02f3f403288a5457fc480c11b2af5df1703ce9170d8f"
}
```

here is the cc-cold.hwsfile (will not help much but i include it anyways):
```json
{
    "type": "ConstitutionalCommitteeColdHWSigningFile_ed25519",
    "description": "Hardware Constitutional Committee Cold Signing File",
    "path": "1852H/1815H/0H/4/0",
    "cborXPubKeyHex": "5840243fcd0c4d6d32fd569c3229e141362ed3cba3caf5edad1cecc240e0c5ac7f3407800eb4db7e6e87d63bd0e84b2b5490f33a2be04400f7a4bf87fa28b61504f8"
}
```

Running the command:
```console
cardano-hw-cli transaction witness \
   --tx-file /tmp/ledger-purple.payment.txbody \
   --hw-signing-file hwCom.cc-cold.hwsfile \
   --hw-signing-file ledger-purple.payment.hwsfile \
   --change-output-key-file ledger-purple.payment.hwsfile \
   --change-output-key-file ledger-purple.staking.hwsfile \
   --testnet-magic 4 \
   --out-file /tmp/ledger-purple.payment.txwitness-coldkey \
   --out-file /tmp/ledger-purple.payment.txwitness-payment
```
causes an error
```
Error: The requested operation failed. Check that your Ledger device is connected, unlocked and with Cardano app running.
Details: Error: Missing signing file for certificate
```

**Pull request merged**
